name: Build themes

on:
  - push
  - pull_request

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create virtual env
        run: python3 -m venv venv

      - name: Install dependencies
        run: venv/bin/pip3 install -r requirements.txt

      - name: Build themes
        run: venv/bin/python3 doki_theme/build_all.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: themes
          path: out/

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/*
